### ISSUE TITLE
Make mime_type_encoding/2 into a hook

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-http#101]
If we want our HTTP server to reply N-Triples, we must include the encoding in the Content-Type header. 
 Since N-Triples is UTF-8 by default, the encoding is redundant:

```http
Content-Type: application/n-triples; charset=utf-8
```

A small improvement would be to turn `mime_type_encoding/2` in module `http_header` into a multi-file predicate:

```prolog
mime_type_encoding('application/json',        utf8).
mime_type_encoding('application/jsonrequest', utf8).
mime_type_encoding('application/x-prolog',    utf8).
```

E.g., ee could extend this list in module `semweb/rdf11` as follows:

```prolog
mime_type_encoding('application/n-quads', utf8).
mime_type_encoding('application/n-triples', utf8).
mime_type_encoding('application/sparql-query', utf8).
mime_type_encoding('application/trig', utf8).
mime_type_encoding('text/turtle', utf8).
```

**Comment by JanWielemaker** [comment]
Ok, pushed 7eaf92e5a5472bb0d89d0f42423e19e9e611b800
