### ISSUE TITLE
uri_query_components/2 does not parse valid semi-colons

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-http#102]
Semi-colons are allowed to appear unescaped in URI query components, but `uri_query_componets/2` is not able to parse them.

**Comment by JanWielemaker** [comment]
Query _components_ are defined as Name=Value pairs.  So yes, `_` is a valid _query_, but it does not have _components_.   This could be an argument to name uri_query_components/2 _fail_ on `_`, but I do not see how it could meaningfully bind `Comps`.

**Comment by wouterbeek** [comment]
Now that I look into this a bit further, the bug is not due to the underscore but due to the semi-colon (issue updated accordingly).

The original use case is:

```uri
https://sameas.cc/terms?term=http:%2F%2Fdbpedia.org%2Fresource%2F%E8%B2%A1%E9%96%A5;_%E3%81%96%E3%81%84%E3%81%B0%E3%81%A4
```

This fails because of the semicolon which is part of the query parameter value.  Abstracting away from some of the specifics:

```prolog
?- uri_query_components('name=val;ue', X).
ERROR: Syntax error: illegal_uri_query
````

Expected answer: `X = [name('val;ue')].`

**Comment by JanWielemaker** [comment]
This still isn't entirely clear as, AFAIK, ';' must be treated as an alternative to '&' and, as I read quickly, ; is a
reserved symbol in the query string.  As I understand we can only do some heuristic matching.  More related
though, the query string doesn't need to be a series of name-value pairs.  What does attempt to break it down?  I think that when processing URIs as identifiers you should not.

**Comment by wouterbeek** [comment]
Thanks Jan, now I understand: whenever we create an API where IRIs can be passed as query arguments we should first escape all occurrence of `&` and `;` in the IRI.
