### ISSUE TITLE
Bug in ws_header for 32 bit machines and payload >= 65536

### ISSUE THREAD

**Issue by abramobagnara** [SWI-Prolog/packages-http#104]
In line 763 we have

    for(i=0; i<8; i++)
      hdr[2+i] = (payload_len >> ((7-i)*8)) & 0xff;

but payload_len has type size_t (i.e. 32 bits on linux 32 bits machines), then
leading to undefined behaviour for shift (and websocket protocol issues).

An easy fix is to change type of payload_len to uint64_t.

**Comment by JanWielemaker** [comment]
Thanks.  I think 5b05ec8ee417e869ca878bb994654af67193603e should fix it.   I don't think payload_len in general needs to change type as we are dealing with a message sent from memory and thus we cannot send such long messages on 32-bit platforms.  Please close if you agree or make a pull request with a proposed fix.
