### ISSUE TITLE
`value_string_as` default value inconsistent between documentation and code

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-http#106]
[The documentation of `json_read_dict/3`](http://www.swi-prolog.org/pldoc/doc_for?object=json_read_dict/2) states that option `value_string_as` has default value `atom`, but the implementation uses `string` as the default:

```prolog
default_json_dict_options(
    json_options(null, true, false, string, '')).
```

Should the documentation or the code be changed to make the default value for this option consistent?

**Comment by JanWielemaker** [comment]
Looks like a copy/paste bug from `json_read/3`.  Pushed a fix.
