### ISSUE TITLE
HTTP Unix daemon library no longer works

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#109]
Please consider the sample server:

<pre>
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_unix_daemon)).

:- http_handler(/, handle_request, []).

handle_request(_Request) :-
    format("Content-type: text/plain~n~n"),
    format("Hello!").
</pre>

The following query *used* to launch the server as a daemon process:

<pre>
$ swipl server.pl --port=5056
</pre>

Using for example SWI 7.7.9 on Debian 9.2, the system does *nothing* but hang on the terminal, and the server seems *not* to launch.

**Comment by JanWielemaker** [comment]
Hmm.  Copied this verbatim and ran on the current devel version.  Runs just fine.  There are some severe bugfixes since, but nothing that directly relates to this AFAIK.  Any messages?  If you send the
output to a file or syslog?  Running with `--interactive`?

**Comment by triska** [comment]
I found the cause of this: The `clib` package had failed to pull and was inexplicably behind `origin/master` by 12&nbsp;commits. I manually pulled the latest version from `origin`, and it now works.

I have high hopes that the work of @dtonhofer on the scripts (such as https://github.com/SWI-Prolog/swipl-devel/pull/288) will prevent similar issues in the future. Thank you!
