### ISSUE TITLE
http_read_data/3 seemingly ignores the input_encoding/1 parameter

### ISSUE THREAD

**Issue by thetrime** [SWI-Prolog/packages-http#116]
This lead to a bit of head-scratching. It seems that the content-type provided by the other party is always respected, but specifying an override has no effect. Is that intentional (in which case, the parameter should be removed) or an accident?

**Comment by spl** [comment]
Fixed by 9bfa494b523685d23722c2a0b7739a6a93d04b8e?

**Comment by JanWielemaker** [comment]
Looks like it is.   If you feel confident, please close.

**Comment by spl** [comment]
GitHub doesn't allow me to close. Only you and @thetrime can. 😁 

I was just using `input_encoding`, and I realized that it was only in the latest stable release (v8.4.1). That's when I discovered this issue.

**Comment by JanWielemaker** [comment]
Ok.   I'll close.   We can always reopen :smile:
