### ISSUE TITLE
Add a hook to json_write to allow for more complicated representations of objects

### ISSUE THREAD

**Issue by thetrime** [SWI-Prolog/packages-http#128]
Currently (as far as I can see) we can only provide custom output in the form of a string via the #/1 mechanism, and the serialize_unknown option, which both produce a JSON string as output.

In the JSON standard at https://tools.ietf.org/html/rfc7159#section-6 it says that it may be *advisable* to use IE7544 double-precision floats for transmitting numbers in JSON (since most recipients are reasonably expected to have facilities to process them) but not *required*, and that it is technically up to the parties themselves to impose any limits on precision if they want to.

I have a use case where I want to transmit numbers with both more (and less) precision than an IE7544 float. I can, of course, just write "0.1", but the receiving party is very insistent that the value should be a number, and not a string, and the sending party is very insistent that the precision of the value must not be diminished. I use an rdiv/2 to represent the number internally, and I know the precision required, so I can turn it into an atom easily enough. I just need to be able to write it on the stream myself - without using quotes - when json_write is trying to process it.

I'll provide a pull request for a sketch of what I mean, in case it's not clear.

**Comment by JanWielemaker** [comment]
Hi Matt,

I see.   What is your plan?  One can see is something like

    json:json_write_hook(float(Digits, Float), Stream) :- 
        ....

and then pass e.g. json_write(_{value:float(20,F)}).

Do you have another idea?   An option?   Please make a PR.

**Comment by thetrime** [comment]
Yes, basically that. I'm making a PR now

**Comment by thetrime** [comment]
That does the trick. 

I just now realised that there's a problem going the other way as well. When we receive a value that we know is a number, we use number_codes/2 to turn it into a float. I would like to instead either allow a hook that I can use to create exact representations of the values as rdiv/2 terms, or provide an option to json_read/3 so that json_read_number/4 (which will become json_read_number/5, I guess) can optionally create an rdiv/2 term for the input.

If you'd prefer I can move this to a new issue and close this one.

**Comment by JanWielemaker** [comment]
Please open a new topic.   Not sure I'm a fan.  In the other direction we could ue otherwise illegal Prolog terms to steer the output, but now we need to map perfectly valid JSON into something new.  How were you planning to do that?
