### ISSUE TITLE
http_reply works differently via http than shell

### ISSUE THREAD

**Issue by honnix** [SWI-Prolog/packages-http#18]
Assume following code

```
test :-
    http_reply(moved('http://a.com'), current_output, [], [], _).
```

When calling `test` from shell, `http_reply` succeeds returning

```
HTTP/1.1 301 Moved Permanently
Date: Tue, 27 Oct 2015 08:52:25 GMT
Location: http://a.com
Content-Length: 370
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html>
<head>
<title>301 Moved Permanently</title>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">

</head>
<body>

<h1>Moved Permanently</h1>

<p>
The document has moved <a href="http://a.com"> Here</a></p>

<address>
<a href="http://www.swi-prolog.org">SWI-Prolog</a> httpd at honnixs-macbook-pro.local
</address>

</body>
</html>
```

However when access `test` via http (browser or curl), following error can be observed:

```
Internal server error

Illegal HTTP parameter: HTTP/1.1 301 Moved Permanently
In:
[30] format(current_output,'~s',[...])
[29] http_header:status_reply('<garbage_collected>',current_output,[],[],'<garbage_collected>') at /usr/local/Cellar/swi-prolog/7.2.3/libexec/lib/swipl-7.2.3/library/http/http_header.pl:329
[28] setup_call_catcher_cleanup(http_header: ...,http_header: ...,_G2190,http_header: ...) at /usr/local/Cellar/swi-prolog/7.2.3/libexec/lib/swipl-7.2.3/boot/init.pl:310
[26] http_header:http_status_reply('<garbage_collected>',current_output,[],[],'<garbage_collected>') at /usr/local/Cellar/swi-prolog/7.2.3/libexec/lib/swipl-7.2.3/library/http/http_header.pl:299
...
```

The error happens when calling `format` and `current_output` is http stream.

**Comment by JanWielemaker** [comment]
What do you mean by "access test via http"?  You cannot use http_reply/5 from an http handler
if you mean that.  The underlying stream demands a CGI formatted document, i.e., 
`<header> \n\n <body>`, where `<header>` is `(<name>: <value>\n)+`.  That is parsed and
handed to http_reply/5.  http_reply/5 is an internal predicate of the HTTP server library.  I
see few cases where it makes sense to call it as a user.

**Comment by honnix** [comment]
Yes, tried to use it from a handler.

The reason using it is to pass additional headers, more specifically in my case `Content_disposition` when reply a file. Of course this can be achieved by using a `format` first and then `http_reply_file`. Just being curious about `http_reply`, whether it can be used for this purpose (looks no though ;) ).

So it is an internal API not supposed to be used by user in general. Then should I use it in this way (it works)?

```
throw(http_reply(file(Type, File), [content_disposition('...')])).
```

**Comment by JanWielemaker** [comment]
Might be better to extend http_reply_file/3, adding an option to pass extra headers.  I'm happy to
get a pull request for that.  See http_open/3 for passing headers through options.

**Comment by honnix** [comment]
That's sounds like a good plan! Will to do it later today. 

Best regards,
Hongxin
