### ISSUE TITLE
Better approach towards throwing HTTP errors

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-http#20]
Better approach towards throwing HTTP errors.  For instance, ClioPatria currently returns the 500 status code for (1) unanticipated but valid request methods (e.g., `OPTIONS`) as well as for (2) unanticipated and malformed requests.

Jan said: "User code can succeed (ok) or throw a http-aware exception (nicely mapped).  That is all fine.  It may also fail or throw any other exception.  This can mean anything.  Sometimes it means the handler didn't check the request properly and fails further down the line.   In most cases it means the handler is broken."

Maybe this can be solved by implementing different **layers** for processing a request, .e.g,:
- Layer 1: Check for request properties that are not supported by the HTTP library (e.g., certain HTTP methods) and return 501 (Not Implemented).
- Layer 2; Check for request properties that are supported by the HTTP library but not implemented by a given HTTP handler (e.g., the handler is only defined for GET but a request has method PUT) and return 405 (Method Not Allowed).
- Layer 3: Check whether the `Content-Type` (if any) is as expected and return 415 (Unsupported Media Type) otherwise.
- Layer 4: Interpret the request's contents according to the `Content-Type`, .e.g, parse a SPARQL request (`application/sparql-query`).  If the parser fails return 400 (Bad Request).
- Layer 5: Process the content parsed in layer 4.  If something goes wrong while processing return 500 (Internal Server Error).
- Layer 6: Check whether the request is authenticated to perform the given method on the specified resource, return 401 (Unauthorized) if this is not the case.
- Layer 7; The processed result of layer 5 is serialized in a response format.  If the `Accept` header of the request did not match any of the serialization options return 406 (Not Acceptable).

The above may be implemented by extending `http_handler/3` with (1) the HTTP method, (2) `Content-Type` (input format to the server), (3) `Accept` (output format from the server), (4) authentication requirements.

Jan said: "The proper way out is probably to extend the `http_handler/3` registration.  That also might allow us to reply to `OPTIONS` and `HEAD` in a generic way.  Probably something like adding `methods(ListOfMethods)` where the default is `methods([get])`."

Many of these layers are present in many real-world requests.  The defaults should make sense in a large set of cases and should be easy to change by the programmer.

**Comment by Anniepoo** [comment]
A basic defect in all of this is that the response code is dealt with not in the handler but in higher levels, and is tied together with a throw.

**Comment by Anniepoo** [comment]
Wouter, do you feel the recent changes have implemented this? Should this close?

**Comment by wouterbeek** [comment]
@Anniepoo I must admit that I am no longer up-to-date on the latest changes in the HTTP library.  Since it could well be the case that this has been implemented/improved in the meantime, I think it is indeed best to close this issue now.
