### ISSUE TITLE
Server cannot handle non-pair URL query values

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/packages-http#21]
Test case:
http://www.swi-prolog.org/xmlrpc.php?rsd

I believe this is from strictly expecting pairs in URL query:
https://github.com/SWI-Prolog/packages-http/blob/f4230cb7948290d3e923d6c00566df44ce4fcb6a/http_header.pl#L1978

**Comment by JanWielemaker** [comment]
Yes.  Not really sure what to do?  Pass the search parameter unparsed?  Of course it is only a real problem if we have an existing client that demands such queries.

**Comment by rla** [comment]
Hm, I did not think about the behavior it should have. I would catch the error and leave `search(ListOfNameValue)` with an empty list. Because there are no pairs.

There is also non-parsed `request_uri(RequestURI)` for those who might want to handle non-pair query parameter themselves.

I would not care about the case when non-pair query parameter does not throw 400 anymore but runs the handler with empty list of parameters. It does not look likely that someone would rely on this exact behavior.

I get hundreds of error reports with error 400 because things try the `/xmlrpc.php?rsd` URL thinking I run PHP. It makes actual error 400 pages (that I should care about) harder to see.

**Comment by JanWielemaker** [comment]
Makes sense.  Pushed a patch for this.  Please close the issue if you think it is ok now.

**Comment by rla** [comment]
Thank you! I patched locally and now I get the expected 404.
