### ISSUE TITLE
Please improve inspection support for redirections

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#23]
First, I suggest the following patch for `http_open.pl` so that the exception is only thrown when the redirection limit is _exceeded_ (as documented):

<pre>diff --git a/http_open.pl b/http_open.pl
index b163883..66478df 100644
--- a/http_open.pl
+++ b/http_open.pl
@@ -657,7 +657,7 @@ do_open(_Version, Code, Comment, _,  _, Parts, _, _, _) :-
 redirect_limit_exceeded(Options, Max) :-
        aggregate_all(count, member(visited(_), Options), N),
        option(max_redirect(Max), Options, 10),
-       (Max == infinite -> fail ; N >= Max).
+       (Max == infinite -> fail ; N > Max).
 
 
 %%     redirect_loop(Parts, Options) is semidet.</pre>

Second, a small feature request: Please add a supported way to reason about redirections. One important use-case for this: A reverse proxy server needs to analyze redirections from the target server, and rewrite them so that they match the client's view of the service. Thus, we cannot even allow a single redirection within `http_open/3` in such use cases, but need to analyze and rewrite all redirections in the chain in general.

Currently, to see whether the target server redirects a request, we can use:

<pre>
catch(http_open(Url, In, [<b>max_redirect(0)</b>]),
      error(<b>permission_error(redirect, _, Redirect)</b>, _), true),
(   nonvar(Redirect) -> ...
;   etc.
)</pre>

But an important information is missing from the exception: The **Code** that was used to redirect. If possible, please:

(1) add the code to the exception and
(2) make this the official way to inspect a redirection, i.e., document the exception term so that user code can rely on it.

Alternatively, please add a different way to easily reason about redirections, fitting the current API. Thank you!

**Comment by JanWielemaker** [comment]
Fixed max_redirect in 65da90b9be8192859f424bc217e686e5fdad8e71.  Added an option redirect(+Boolean) in cedf940f19564e94e27cbbaba35e8387842d742c:

```
2 ?- http_open('http://swi-prolog.org', In, [redirect(false), status_code(Code), headers(Headers)]).
In = <stream>(0x24dec10,0x2408830),
Code = 303,
Headers = [ server('nginx/1.9.6'), 
                    date('Fri, 13 Nov 2015 08:53:58 GMT'), 
                    content_type('text/html'), 
                    content_length(168), 
                    connection(close),
                    location('http://www.swi-prolog.org/')
                   ].
```

Using an exception is not a good idea as you may want to read the other headers and/or the content of the reply.
