### ISSUE TITLE
Running SWI-Prolog HTTPS services as Unix daemons

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#25]
A simple skeleton for an HTTPS server is:

```
https_server(Port) :-
        http_server(http_dispatch,
                    [ port(Port),
                      ssl([ ...])
                    ]).
```

where the `ssl(....)` option is suitably filled with certificate etc. Everything works nicely.

I now want to start the server from a systemd or init.d startup script. Alas, the `http_unix_daemon` library does not seem to support HTTPS. I would prefer to start the server with something similar to:

<pre>
$ swipl -s server.pl -- --user=my_user --port=443 <b>--ssl=true --cert=... etc.</b>
</pre>

Since this does not work, what can I do instead? First, it obviously needs to run as root to make the service available on port 443. To drop root privileges, I change the above code to:

<pre>
https_server(Port) :-
        http_server(http_dispatch,
                    [ port(Port),
                      ssl([ ...])
                    ]),
        <b>set_user_and_group(my_user)</b>.
</pre>

and then I can successfully do:

```
$ swipl -f server.pl -g 'https_server(443)'
```

to make the server available.

But this starts an interactive shell instead of detaching the process, so it is not yet suitable for use in init scripts. The next attempt is typically similar to:

<pre>
$ swipl -f server.pl -g 'https_server(443)' <b>&</b>
</pre>

But then the process will receive `SIGHUP` and terminate when SWI next asks for user input. So we can use `nohup` in combination with `&`, `disown -h` etc., all just to run the process somehow in the background.

Is there any recommendation regarding how to start SWI HTTPS servers in the background? Obviously, extending `http_unix_daemon.pl` is the most preferable solution. If that is not possible, then I think a simple predicate that just means "serve all arriving HTTP(S) clients" would be useful, because it would allow us to say:

<pre>
$ swipl -f server.pl -g 'https_server(443),<b>serve_all_clients</b>' &
</pre>

and that would prevent SWI-Prolog from asking for more input and thus avoid the `SIGHUP` if the process is detached.

**Comment by JanWielemaker** [comment]
There is a hook that keeps all the daemon interaction and lets you start the server any way you please:
- http://www.swi-prolog.org/pldoc/doc_for?object=http_unix_daemon%3Ahttp_server_hook/1

In due time, it would be nice to get ssl almost out of the box.  I'm particularly interested in
[let's encrypt](https://letsencrypt.org/).  Anything else that helps getting the right certificate files and telling the SSL layer to use them is welcome ...

**Comment by triska** [comment]
I've tried my luck with pull request #26. With this patch, you can run an HTTPS server with:

<pre>swipl -f server.pl -- --port=443 --user=you <b>--https --certfile</b>=server.crt <b>--keyfile</b>=server.key</pre>

**Comment by JanWielemaker** [comment]
Merged.
