### ISSUE TITLE
Running Unix daemon without --interactive ignores other source files

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#28]
Take for example [Proloxy](https://github.com/triska/proloxy):

When I run

<pre>
$ swipl <b>-l config.pl</b> -f proloxy.pl -- --port=3030  <b>--interactive</b>
</pre>

then, as expected, the Prolog rules contained in **config.pl** are available to the program, and HTTP dispatching works exactly as intended.

However, when I drop the `--interactive` switch and use:

<pre>
$ swipl <b>-l config.pl</b> -f proloxy.pl -- --port=3030
</pre>

then I get, when accessing the web server on port 3030:

`Undefined procedure: request_prefix_target/3`

It thus seems that the additional source file (config.pl) is only loaded when I use the `--interactive` switch.

The use case for this is clear: I want to make additional rules easily available by specifying further source files on the command line. For consistency and to benefit from this feature, I hope they can be loaded as specified also when omitting the `--interactive` switch.

**Comment by JanWielemaker** [comment]
-l, etc are all backward/YAP/... compatibility.  AFAIK, the following simply works

```
swipl config.pl proloxy.pl --port=3030
```

The overall syntax is 

```
swipl [prolog options] [prolog source files] [application options]
```

This also causes clean cooperation with Unix `#!` scripts.  Note that `current_prolog_flag(argv, AV)` picks only the application options.

**Comment by triska** [comment]
Thank you, I have added an entry that documents this in the [pull request](https://github.com/SWI-Prolog/swipl-devel/pull/98).
