### ISSUE TITLE
HEAD method must not return a message-body in the response

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#31]
Quoting from [W3.org](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html):

> The HEAD method is identical to GET except that the server **MUST NOT** return a message-body in 
> the response. The metainformation contained in the HTTP headers in response to a HEAD request
> SHOULD be identical to the information sent in response to a GET request. This method can be used
> for obtaining metainformation about the entity implied by the request without transferring the 
> entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and 
> recent modification.

Currently, when I telnet to an SWI-Prolog HTTP server and ask:

```
HEAD /
```

then I get a message-body _in addition_ to the requested head. This noncomformant  response is very undesirable for several reasons. If possible, please avoid replying the message body when responding to `HEAD` requests. Thank you!

**Comment by wouterbeek** [comment]
This requires the HTTP libraries to make a distinction between a stream where headers are written to and a stream where the body is written to.  We can then implement a HEAD reply by setting the latter to a null stream (`open_null_stream/1`).

To give a concrete example, `format/1` should write to another stream than `json_write_dict/2`:

``` prolog
reply_json_dict(Dict) :-
    format('Content-type: application/json; charset=UTF-8~n~n'),
    json_write_dict(current_output, Dict).
```

**Comment by wouterbeek** [comment]
Oops, this has to be done in the C CGI script...  deassigned myself :-(  Anyone with C-skills who wants to do this?

**Comment by wouterbeek** [comment]
This seems to be more than a nicety considering the following excerpt from Raivo's blog:

> The HEAD requests are replied with full body. Some clients do not expect that and close connection. The result is error lines from socket errors and false alerts. I could disable alerts but then I have other things not working and I'm not even knowing about them. I cannot fix this from SWI because it's not flexible enough. I cannot fix this from Nginx because it does not expect and support such use cases. I have currently "fixed" it by returning 405 (Method not allowed). That is what Nginx can do for me.

**Comment by triska** [comment]
It's indeed more than a nicety to _not_ do something when the standard tells you that you _must&nbsp;not_ do it. As the blog post also shows, doing what the standard precludes is a bit unexpected for conformant programs, to say the least.

**Comment by triska** [comment]
This is fixed now, thank you very much Jan for this awesome feature!
