### ISSUE TITLE
Keep-alive connections can cause extreme performance degradation

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#33]
Steps to reproduce (7.3.14/latest git version):
1. Clone [Proloxy](https://github.com/triska/proloxy)
2. Install [shellinabox](https://github.com/shellinabox/shellinabox)
3. Start shellinabox with:
   
   ```
   $ shellinaboxd  --disable-ssl --localhost-only
   ```
   
   You can now access shellinabox on `http://localhost:4200` to see that it works correctly.
4. Let `shellinabox.pl` consist of the single clause:
   
   ```
   request_prefix_target(Request, '', TargetURI) :-
           memberchk(request_uri(URI), Request),
           atomic_list_concat(['http://localhost:4200',URI], TargetURI).
   ```
5. Start Proloxy with:
   
   ```
   $ swipl shellinabox.pl proloxy.pl --interactive --port=4041
   ```
   
   You can now access Proloxy on `http://localhost:4041`, and it will relay all traffic to the shellinabox server behind the scenes. At this point, everything should work quite smoothly (awesome SWI HTTP libraries!), with roundtrip times in the millisecond range. If you look at the HTTP traffic, you will see though that, contrary to what the manual states, `Keep-alive` is **not** the default for the answers of Proloxy: Its replies to requests contain the header field `Connection: close`.
6. To enable Keep-alive connections between the client and Proloxy, we need to patch Proloxy to reply with `Connection: Keep-Alive`, using the patch shown below. If you apply the patch, then restart Proloxy, and again go to `http://localhost:4041`, performance will be **severely degraded**. Roundtrip times increase thousands of times, and responses now take several _seconds_.

Please let me know whether this is the correct way to enable Keep-alive connections, or alternatively please enable Keep-alive connections per default (as stated in the manual) also for the kind of answers that Proloxy uses.

Note that the communication between Proloxy and shellinabox is not and need not be `Keep-alive`, because these reside on the same machine and the overhead for setting up an HTTP connection is low. My eventual goal is to enable completely transparent keep-alive connections _over the proxy_ too, but for that at least the Client <-> Proloxy connection (which is the focus of this issue) must work efficiently too.

Here is the patch, which just adds `Connection: Keep-alive` to the headers of Proloxy responses:

<pre>
diff --git a/proloxy.pl b/proloxy.pl
index 1db8685..d7aa81a 100644
--- a/proloxy.pl
+++ b/proloxy.pl
@@ -80,7 +80,7 @@ proxy(data(Method), _, _, TargetURI, Request) :-
                                   header(content_type, ContentType)]),
         call_cleanup(read_string(In, _, Bytes),
                      close(In)),
-        throw(http_reply(bytes(ContentType, Bytes))).
+        throw(http_reply(bytes(ContentType, Bytes), <b>[connection('Keep-Alive')]</b>)).
 proxy(other(Method), Prefix, URI, TargetURI, _) :-
         http_open(TargetURI, In, [method(Method),
                                   % cert_verify_hook(cert_accept_any),
@@ -99,7 +99,7 @@ proxy(other(Method), Prefix, URI, TargetURI, _) :-
             throw(http_reply(Reply))
         ;   Code == 404 ->
             throw(http_reply(not_found(URI)))
-        ;   throw(http_reply(bytes(ContentType, Bytes)))
+        ;   throw(http_reply(bytes(ContentType, Bytes), <b>[connection('Keep-Alive')]</b>))
         ).
 
 redirect_code(301, moved).
</pre>

**Comment by JanWielemaker** [comment]
The obvious thing is that the proxy server doesn't have enough threads,
so new connections will have to wait until a worker waiting for a
keep-alive gets a timeout.  There are roughly three ways out:
- Just start more workers.  Might be a little costly if there
  is not that much traffic.
- Use the `spawn` option to put new clients on a new thread.
  Can run out of threads.  You can use the thread-pool mechanism
  to limit the number of threads it can start this way.
- Use the hook http:schedule_workers/1 to monitor the resource
  allocation and dynamically add or remove workers.

The ideal solution depends a lot on what you are doing and thus
which resource (threads, memory, CPU, sockets) is most critical.
The above is more or less ordered low-to-high complexity and
sophistication.

```
Cheers --- Jan
```

**Comment by triska** [comment]
I have now reduced this issue to the essence (note that increasing the number of workers does not help in this case, since both issues only involve a single HTTP request):
1. Let `server.pl` consist of:
   
   ```
   :- module(server,
             []).
   
   :- use_module(library(http/thread_httpd)).
   :- use_module(library(http/http_dispatch)).
   :- use_module(library(http/http_unix_daemon)).
   
   :- initialization http_daemon.
   
   :- http_handler(/, handle_request, [prefix]).
   
   handle_request(_) :-
           throw(http_reply(bytes('text/plain', "hello"))).
   ```
2. Start SWI-Prolog with:
   
   ```
   $ swipl server.pl --port=5050 --interactive --workers=16
   ```
3. Go to `http://localhost:5050`.
4. **First issue**: From the reply headers, you see that the server responds with `Connection: close` in the header fields, although the manual states in Section&nbsp;3.1 that `Keep-Alive` is the default.
5. **Second issue**: If I manually force `connection('Keep-Alive')` in `handle_request/1` above, i.e, when I have:
   
   ```
   handle_request(_) :-
           throw(http_reply(bytes('text/plain', "hello"), [connection('Keep-Alive')])).
   ```
   
   and then again go to `http://localhost:5050`, then the request only finishes after **2 seconds** of delay.

**Comment by triska** [comment]
I have created a pull request that fixes both issues ;-)

**Comment by JanWielemaker** [comment]
Thanks for sorting this out!  Merged.
