### ISSUE TITLE
--ip=IP option is broken

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#54]
Let `server.pl` consist of:

```
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_unix_daemon)).

:- initialization http_daemon.

:- http_handler(/, write_index, []).

write_index(_Request) :-
    format("Content-type: text/plain~n~n"),
    format("hello!!").
```

When I do:

<pre>
$ swipl server.pl --port=5050 --interactive 
</pre>

then everything works exactly as expected.

In contrast, when I do (`--ip=localhost` is an example that is shown when using `--help`):

<pre>
$ swipl server.pl --port=5050 --interactive <b>--ip=localhost</b> 
</pre>

I get:

<pre>
ERROR: ssl:'_ssl_context'/4: Arguments are not sufficiently instantiated
</pre>

The **--ip** option  is broken since **7.3.23**.

I am filing this as an issue instead of submitting a pull request right away because I have a bit of feedback on the options processing code: As this issue shows, overloading the various options with different syntax variants to specify ports and addresses in several ways makes the code a lot harder to test and quite fragile.

Please let us reflect a moment if it is not better to keep the `--port` and `--ip` options cleanly separated from the `--http` and `--https` options. If&mdash;as was the case until very recently!&mdash; there were only **one&nbsp;way** to specify each&nbsp;of:
- **protocol** (`--http` or `--https`)
- **port** (`--port=...`) and
- **address** (`--ip=...`)

then I think this issue would have been found _a lot_ earlier, and most likely on the SWI site itself.

**Comment by JanWielemaker** [comment]
> I am filing this as an issue instead of submitting a pull request right away because I have a bit of feedback on the options processing code: As this issue shows, overloading the various options with different syntax variants to specify ports and addresses in several ways makes the code a lot harder to test and quite fragile.

To some extend that is true.  This started of looking for a natural way to start multiple servers.  Basically one does not like option ordering to be important, so `--http=port' seemed a sensible option to consider. Handling of the other options came from the requirement for backward compatibility as well as the requirement to have some rather non-standard options specific to a certain server.   Now, the option joining code is fairly complex.  Most of the complexity comes from the ordering and default handling.   I think it is acceptable and definitely not a good idea to break compatibility.

Pushed a patch.

Still wondering whether it might be a better idea to use a configuration file ...

**Comment by wouterbeek** [comment]
+1 for a config file.  Since we have Prolog we do not need XML, YAML, etc.

**Comment by JanWielemaker** [comment]
I'm not that sure.  Basically all the stuff such as locations, authentication, etc is handled in the server.   The `http_unix_daemon.pl` wrapper only does:
- Create one or more HTTP/HTTPS servers.   For HTTPS you might want a config file telling
  the server where the certificate is, what the password is, etc.
- Do the Unix daemon integration.   Depending on whether you start it from SysV scripts, upstart
  or systemd or whatever you need different options.  That is not what you want in a config file but
  in the call from daemon configuration you are using.
- Development options (debugging, tracing, run in foreground, expose the toplevel, etc).  None of
  these you want from a config file (I think).   If you often want a particular config during development,
  just write a shell script.

So, what would you like to have in the config file?

**Comment by triska** [comment]
In general, I also like the flexibility of command line options very much. In the case of HTTPS, I am quite certain that we will need a config file to sensibly support server-side&nbsp;SNI. I will file a separate issue for this, explaining this in more detail. Please let us continue the discussion about the best format for this file in that issue. I agree that most other options can also remain on the command line. Strictly speaking, it could be possible to support even SNI by command line options alone, but there are some important reasons to provide a config file for this regardless:
1. the command line for such a complex configuration option may simply get too long on some systems
2. even if (1) were not the case, the command line will get too long to conveniently edit it
3. even if (1) and (2) were not the case, the command line may become too hard to understand due to the somewhat complex interactions of the options and their order.

Also, I find Prolog-based config files a good way to **advertise declarative Prolog fragments**!

The present issue is fixed, so I will close it unless there is something left to discuss. I for one am still under the impression that the option processing code is unnecessarily complex due to the multiple redundant ways to specify the available options. In my view, it would be complex enough even without such a multitude of variations. On the plus side, at least there is no ambiguity (yet) for interfaces called `true` and `false`, which would cause impressive issues when used with `--https=true` etc. ;-)

Thank you for the fast correction!

**Comment by triska** [comment]
Thank you for correcting this!
