### ISSUE TITLE
http_log.pl: improve logging of http_reply(Reply, Options) case

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#7]
It seems that `http_log.pl` would benefit from:

```
map_exception(http_reply(Reply,_), Reply).
```

or something similar, so that replies of the form `http_reply(Reply, Options)` are logged as expected. Otherwise, we see terms like:

`error("Unknown message: http_reply(stream(<stream>(0x7f916287dbf0),137) ...)`

in `httpd.log` when for example replying with `http_reply(stream(S), [...])`.

However, one benefit of the current logging is that the file contains syntactically valid Prolog terms, whereas `<stream>(...)` is (of course intentionally) not a valid Prolog term, so especially in connection with the `stream(S)` option, care should be taken to preserve valid Prolog syntax in the log file.

**Comment by JanWielemaker** [comment]
Thanks.  Added.

**Comment by triska** [comment]
Thank you! I think the current fix can lead to problems: If the first argument is a stream (i.e., the reply was generated with `throw(http_reply(stream(In,Size), [])`), then you end up with `httpd.log` no longer parseable because it will contain lines like:

<pre>
completed(31, 0.0015320000000000004, 4, 200, stream(<b>&lt;stream&gt;(0x7fe4530436c0)</b>,4)).
</pre>

**Comment by JanWielemaker** [comment]
Yip.  Pushed 8e18226338d1e3f00e12a8f78d250b28951c5a17
