### ISSUE TITLE
http_reply/[2,3,4] fail unexpectedly

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#8]
Currently, only the 5-argument version of `http_reply` works as documented:

```
?- http_reply(html([]), current_output, [], [], C).
HTTP/1.1 200 OK ...
C = 200.
```

If I omit any of the optional arguments, which should work according to the documentation, I get `false` in all cases:

```
?- http_reply(html([]), current_output, [], C).
false.

?- http_reply(html([]), current_output, []).
false.

?- http_reply(html([]), current_output).
false. 
```

**Comment by triska** [comment]
Awesome contribution, many thanks @honnix!

**Comment by honnix** [comment]
@triska You are welcome.
