### ISSUE TITLE
Every second request is rejected (OPTIONS request).

### ISSUE THREAD

**Issue by CodiePP** [SWI-Prolog/packages-http#89]
I am trying to connect a Backbone.js app (the demo Todo list) via REST to SWI-Prolog.
![scr01](https://cloud.githubusercontent.com/assets/14063171/25642431/fd54e570-2f99-11e7-8783-fc6f00d9c7a6.png)

The js-app makes calls to GET and POST. The latter is preceded by an OPTIONS request. I can savely handle this one and the POST gets through. Except that in every second POST request some old input data is added to the OPTIONS handler. And this then leads to the "Bad Request" as shown in the logfile excerpt from below:

`/*Wed May  3 00:40:52 2017*/ request(1, 1493764852.433, [peer(ip(127,0,0,1)),**method(get)**,request_uri('/todo1'),path('/todo1'),http_version(1-1),host(localhost),port(3001),user_agent('Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0'),referer('http://localhost:3000/index.html'),origin('http://localhost:3000'),dnt('1'),connection('keep-alive')]).
completed(1, 0.0009339069999999999, 826, 200, ok).

/*Wed May  3 00:40:55 2017*/ request(2, 1493764855.670, [peer(ip(127,0,0,1)),**method(options)**,request_uri('/todo1'),path('/todo1'),http_version(1-1),host(localhost),port(3001),user_agent('Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0'),access_control_request_method('POST'),access_control_request_headers('content-type'),origin('http://localhost:3000'),dnt('1'),connection('keep-alive')]).
completed(2, 0.002140802, 0, 200, ok).

/*Wed May  3 00:40:55 2017*/ request(3, 1493764855.699, [peer(ip(127,0,0,1)),**method(post)**,request_uri('/todo1'),path('/todo1'),http_version(1-1),host(localhost),port(3001),user_agent('Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0'),content_type('application/json'),referer('http://localhost:3000/index.html'),content_length(42),origin('http://localhost:3000'),dnt('1'),connection('keep-alive')]).
completed(3, 0.0010439790000000004, 897, 200, ok).

completed(0, 0.0028612840000000004, 389, 400, error("Illegal HTTP request: _{\"title\":\"11\",\"completed\":false,\"order\":1}_**OPTIONS** /todo1 HTTP/1.1 (in_http_request)")).
`
As wireshark confirmed that these data did not go over the wire and was not part of the OPTIONS request sent, I assume it must be in some buffer that is not reset.
I would be very happy to get any hints where to start searching for this in the code base.
Thanks for your help.

**Comment by JanWielemaker** [comment]
This looks like you do a POST, but the POST implementation is not reading the posted data or at least 
not all of it.  The implementation MUST call http_read_json_dict/2 or one of the other HTTP message reading predicates to read the data.  Otherwise the next request on the keep-alive connection will read the data.

**Comment by CodiePP** [comment]
Thank you. That did the job and I am happy again. :-)
