### ISSUE TITLE
Better SSL error messages (e.g., when setting port 80)?

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-http#96]
Port 80 is not the correct port for HTTPS requests of course, but the error message is currently not very descriptive:

```prolog
?- use_module(library(http/http_open)).
?- use_module(library(http/http_ssl_plugin)).
?- http_open('https://aap.nl:80', In, [cert_verify_hook(cert_accept_any)]).
ERROR: SSL(140770FC) func(119): reason(252)
```

Is there an existing mapping from SSL error codes to human-readable descriptions that can help the programmer a bit better?

**Comment by JanWielemaker** [comment]
This is an issue for the SSL package.  https://www.openssl.org/docs/man1.0.2/crypto/err.html suggests that it is possible to get human readable error messages.  Opened there.  I close this here.
